// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace RecipeManager
{
	public partial class RecipePickerViewController : UIViewController
	{
		public MainCalendarViewController Delegate { get; set; }
		public RecipePickerViewController (IntPtr handle) : base (handle)
		{
		}
		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
		}
	}
}
