// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace RecipeManager
{
	public partial class ScheduleRecipeViewController : UIViewController
	{
		public HomeViewController Delegate { get; set; }
		public ScheduleRecipeViewController(IntPtr handle) : base(handle)
		{
		}
		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			Title = "Weekly Shopping List";
		}

	}
}
