// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using CoreGraphics;
using Foundation;
using UIKit;

namespace RecipeManager
{
	public partial class SearchResultsViewController : UIViewController
	{
		//ResultsTableViewController resultsTableController;
		//UISearchController searchController;
		//bool searchControllerWasActive;
		//bool searchControllerSearchFieldWasFirstResponder;
		IEnumerable<Recipe> resultsTableItems;
		//List<SearchItem> searchResults;
		UISearchBar searchBar;

		public SearchResultsViewController (IntPtr handle) : base (handle)
		{
		}
		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			//resultsTableItems = AppDelegate.RecipesDB.GetRecipesList();


			Title = "Search";
			//SearchResultsTableView.Source = new SearchResultsTableViewSource(resultsTableItems);

			searchBar = new UISearchBar();
			searchBar.Placeholder = "Search by title, calories, or cook time";
			searchBar.SizeToFit();
			searchBar.AutocorrectionType = UITextAutocorrectionType.No;
			searchBar.AutocapitalizationType = UITextAutocapitalizationType.None;
			searchBar.SearchButtonClicked += (sender, e) =>
			{
				//TODO: error checking for if one of the buttons is not selected
				Search();
			};

			SearchResultsTableView.TableHeaderView = searchBar;
		}
		public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);
			SearchResultsTableView.ContentInset = new UIEdgeInsets(-60, 0, 0, 0);
		}

		partial void RecipeTitleFilterButtonSelected(NSObject sender)
		{
			RecipeTitleFilterButton.Highlighted = true;
			RecipeTitleFilterButton.BackgroundColor = UIColor.LightGray;
			CalorieCountFilterButton.BackgroundColor = UIColor.White;
			CookTimeFilterButton.BackgroundColor = UIColor.White;
		}
		partial void CalorieCountFilterButtonSelected(NSObject sender)
		{
			CalorieCountFilterButton.Highlighted = true;
			CalorieCountFilterButton.BackgroundColor = UIColor.LightGray;
			RecipeTitleFilterButton.BackgroundColor = UIColor.White;
			CookTimeFilterButton.BackgroundColor = UIColor.White;
		}
		partial void CookTimeFilterButtonSelected(NSObject sender)
		{
			CookTimeFilterButton.Highlighted = true;
			CookTimeFilterButton.BackgroundColor = UIColor.LightGray;
			CalorieCountFilterButton.BackgroundColor = UIColor.White;
			RecipeTitleFilterButton.BackgroundColor = UIColor.White;
		}

		public void Search()
		{
			if (!string.IsNullOrEmpty(searchBar.Text))
			{
				if (RecipeTitleFilterButton.BackgroundColor == UIColor.LightGray)
					resultsTableItems = AppDelegate.RecipesDB.SearchByRecipeTitle(searchBar.Text);
				else if (CalorieCountFilterButton.BackgroundColor == UIColor.LightGray) // error handling
					resultsTableItems = AppDelegate.RecipesDB.SearchByCalories(Convert.ToInt32(searchBar.Text));
				else if (CookTimeFilterButton.BackgroundColor == UIColor.LightGray) // error handling
					resultsTableItems = AppDelegate.RecipesDB.SearchByCookTime(Convert.ToInt32(searchBar.Text));
			}

			searchBar.Text = "";
			SearchResultsTableView.Source = new SearchResultsTableViewSource(resultsTableItems);
			SearchResultsTableView.ReloadData();
		}

	}
}