// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

namespace RecipeManager
{
	public partial class WeeklyShoppingListViewController : UIViewController
	{
		IEnumerable<Ingredient> shoppingListsTableItems;
		public HomeViewController Delegate { get; set; }

		public WeeklyShoppingListViewController (IntPtr handle) : base (handle)
		{
		}
		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			Title = "Weekly Shopping List";
		}
		public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);
			ShoppingListTableView.ContentInset = new UIEdgeInsets(-60, 0, 0, 0);
			shoppingListsTableItems = AppDelegate.RecipesDB.GetWeeklyShoppingList();
			ShoppingListTableView.Source = new IngredientsTableViewSource(shoppingListsTableItems);
			ShoppingListTableView.ReloadData();
		}
	}
}
